config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers:{
              path: "",
              path_names: {sign_up: "register", sign_in: "login", edit: "profile", sign_out: "logout"},
              controllers: {registrations: "registrations"}}

  resources :rooms, except: [:edit] do
    collection do
      get "search"
    end

    member do
      get "listing"
      get "pricing"
      get "description"
      get "photo_upload"
      get "location"
      delete :delete_photo
      post :upload_photo
    end

    resources :reservations
  end

  resources :reservations do
    member do
      get "confirm"
    end
  end

  get "pages/home"
  get "/account", to: "users#account"
  get "/dashboard", to: "users#dashboard"
  get "/users/:id", to: "users#show", as: "user"
  get "rooms/new", to: "rooms#new"
  get "/your_trips" => "reservations#your_trips"
  get "/your_reservations" => "reservations#your_reservations"
  get "search" => "pages#search"

  post "/users/edit", to: "users#update"

  root to: "pages#home"



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room
  has_one :trip

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :number_of_guests, presence: true, numericality: { greater_than: 0 }
  validate :start_end_check

  def start_end_check
      if self.start_date.present? && self.end_date.present?
          errors.add(:end_date, "は開始日より前の日付は登録できません。") unless
          self.start_date <= self.end_date
      end
  end

  def total_price
    if end_date.present? && end_date.present? && room.price? && number_of_guests?
      (end_date.to_date - start_date.to_date).to_i * room.price * number_of_guests
    else
      0
    end
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
    before_action :authenticate_user!

    def new
        @reservation = Reservation.new
    end

    def create
        @room = Room.find(params[:room_id])

        @reservation = current_user.reservations.new(reservation_params)
        @reservation.room = @room
        @reservation.price = @room.price

        if @reservation.save
            redirect_to confirm_reservation_path(@reservation.id)
        else
            render "rooms/show", status: :unprocessable_entity
        end
    end

    def your_trips
        @trips = current_user.reservations.order(start_date: :asc)
    end

    def your_reservations
        @rooms = current_user.rooms
        @trips = current_user.reservations.order(start_date: :asc)
    end

    def confirm
        @reservation = Reservation.find(params[:id])
        @reservation.total_price
        @reservation.save
    end

    def update
        @reservation = Reservation.find(params[:id])
        if @reservation.save
            if @reservation.update(reservation_params)
            end
            flash[:notice]= "保存しました。"
            redirect_to root_path
        else
            render :confirm
        end
    end

    private

    def reservation_params
        params.require(:reservation).permit(:start_date, :end_date, :number_of_guests)
    end

end

app/views/reservations/confirm.html.erb
<div class="row" style="margin-left: 10px; margin-right: 10px">
  <div class="col-md-8">
    <br />
    <div class="row">
      <div class="col-md-11">
        <div class="card">
          <div class="card-body">
            <h3>予約確認</h3>
            <div class="card" style="width: 24rem; margin-left: 70px">
              <div class="card-body">
                <table>
                  <tr>
                    <p>チェックイン: <%= I18n.l(@reservation.start_date, format: :full_date) %></p>
                  </tr>
                  <tr>
                    <p>チェックアウト: <%= I18n.l(@reservation.end_date, format: :full_date) %></p>
                  </tr>
                  <tr>
                    <p>宿泊日数: <%= (@reservation.end_date.to_date - @reservation.start_date.to_date).to_i %> 泊</p>
                  </tr>
                  <tr>
                    <p>人数: <%= @reservation.number_of_guests %></p>
                  </tr>
                  <tr>
                    <p>支払金額: <%= number_to_currency(@reservation.total_price) %></p>
                  </tr>
                </table>
                <br />
                <%= form_with(model: @reservation, url: reservation_path, local: true) do |f| %> 
                <%= f.hidden_field :step, value: "confirm" %>
                <%= f.submit "予約を確定する", id: "btn_book", class:"btn btn-danger btn-block"%> 
                <% end %>
              </div>
            </div>
            <%= link_to "戻る", :back %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<br />

app/views/reservations/your_reservations.html.erb
<div class="row" style="margin-top: 50px; margin-left: 30px">
  <div class="card">
    <h3 style="margin-top: 30px; margin-left: 30px">登録施設一覧</h3>
    <br />
    <table class="table table-striped">
      <thead>
        <tr>
          <th>施設画像</th>
          <th>施設名</th>
          <th>紹介文</th>
          <th>宿泊料金（一泊）</th>
          <th>作成日</th>
        </tr>
      </thead>
      <tbody>
        <% if @rooms.blank? %>
        <tr>
          <td colspan="7" class="has-text-cenrered">
            <h1>表示できる登録施設はありません。</h1>
          </td>
        </tr>
        <% end %> 
        <% @rooms.each do |room| %>
        <tr>
          <td>
            <% if room %> 
              <%= link_to room_path(room), data: { turbolinks: false} do %> 

            <% if room.photos.attached? %> 
              <%= image_tag room.photos.first, style: "width: 230px;" %><br />

              <% else %> 
                <%= image_tag "default_image_room.png", style: "width: 230px;" %> 
            <% end %> 
            <% end %> 
            <% end %>
          </td>

          <td><%= link_to room.room_type, room_path(room), data: { turbolinks: false} %></td>

          <td><%= room.summary %></td>

          <td><%= number_to_currency(room.price) %></td>

          <td><%= I18n.l(room.created_at, format: :full_date) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br />

app/views/reservations/your_trips.html.erb
<div class="row" style="margin-top: 50px; margin-left: 30px">
  <div class="card">
    <h3 style="margin-top: 30px; margin-left: 30px">予約一覧</h3>
    <br />
    <table class="table table-striped">
      <thead>
        <tr>
          <th>施設画像</th>
          <th>施設名</th>
          <th>紹介文</th>
          <th>人数</th>
          <th>合計金額</th>
          <th>チェックイン</th>
          <th>チェックアウト</th>
          <th>予約確定日時</th>
        </tr>
      </thead>
      <tbody>
        <% if @trips.blank? %>
        <tr>
          <td colspan="7" class="has-text-cenrered">
            <h1>表示できるご予約はありません。</h1>
          </td>
        </tr>
        <% end %> <% @trips.each do |trip| %>
        <tr>
          <td>
            <% if trip.room %>
              <%= link_to room_path(trip.room), data: { turbolinks: false} do %>
                <% if trip.room.photos.attached? %>
                  <%= image_tag trip.room.photos.first, style: "width: 230px;" %><br>
                <% else %> 
                  <%= image_tag "default_image_room.png", style: "width: 230px;" %> 
                <% end %> 
              <% end %> 
            <% end %>
          </td>

          <td><%= link_to trip.room.room_type, room_path(trip.room), data: { turbolinks: false} %></td>

          <td><%= trip.room.summary %></td>

          <td><%= trip.number_of_guests %> 人</td>

          <td><%= number_to_currency(trip.total_price) %></td>

          <td><%= I18n.l(trip.start_date, format: :full_date) %></td>

          <td><%= I18n.l(trip.end_date, format: :full_date) %></td>

          <td><%= I18n.l(trip.created_at, format: :long) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br />