config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers:{
              path: "",
              path_names: {sign_up: "register", sign_in: "login", edit: "profile", sign_out: "logout"},
              controllers: {registrations: "registrations"}}

  resources :rooms, except: [:edit] do
    collection do
      get "search"
    end

    member do
      get "listing"
      get "pricing"
      get "description"
      get "photo_upload"
      get "location"
      delete :delete_photo
      post :upload_photo
    end

    resources :reservations
  end

  resources :reservations do
    member do
      get "confirm"
    end
  end

  get "pages/home"
  get "/account", to: "users#account"
  get "/dashboard", to: "users#dashboard"
  get "/users/:id", to: "users#show", as: "user"
  get "rooms/new", to: "rooms#new"
  get "/your_trips" => "reservations#your_trips"
  get "/your_reservations" => "reservations#your_reservations"
  get "search" => "pages#search"

  post "/users/edit", to: "users#update"

  root to: "pages#home"



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord

  belongs_to :user

  has_many :reservations
  has_many :photos
  has_one_attached :avatar
  has_many_attached :photos
  has_many_attached :images

  validates :room_type, presence: true
  validates :summary, presence: true
  validates :price, presence: true
  validates :address, presence: true

  def self.ransackable_associations(auth_object = nil)
    ["images", "reservations", "user"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["address", "room_type", "summary"]
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  protect_from_forgery except: [:upload_photo]

  before_action :set_room, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:show]
  before_action :authorize_user, only: [:listing, :pricing, :description, :photo_upload, :location, :update]

  def index
    @rooms = current_user.rooms
  end

  def new
    @room = Room.new

  end

  def create
    @room = current_user.rooms.build(room_params)
    if @room.save

      flash[:notice]= "保存しました。"
      redirect_to root_path
    end
  end

  def show
    @reservation = Reservation.new
    @photos = @room.photos
  end

  def listing
  end

  def pricing
  end

  def description
  end

  def photo_upload
  end

  def amenities
  end

  def location
  end

  def update

    new_params = room_params
    new_params[:active] = true if is_ready_room

    if @room.update(new_params)
      flash[:notice] = "保存しました。"
    else
      flash[:alert] = "問題が発生しました。"
    end
      redirect_back(fallback_location: request.referrer)
  end

  def upload_photo
    @room.photos.attach(params[:file])
    render json: { success:true }
  end

  def delete_photo
    @image = ActiveStorage::Attacchment.find(params[:photo_id])
    @image.purge
    redirect_to photo_upload_room_path(@room)
  end


  private

    def set_room
      @room = Room.find(params[:id])
    end

    def room_params
      params.require(:room).permit(:room_type, :listing_name, :summary, :price, :address, :active, :description, :avatar, :image, :photos )
    end

    def authorize_user
      redirect_to root_path, alert:"権限がありません。" unless current_user.id == @room.user_id
    end

    def is_ready_room
      !@room.active && !@room.price.blank? && !@room.listing_name.blank? && !@room.photos.blank? && !@room.address.blank?
    end

    def is_conflict(start_date, end_date, room)
      room.reservations.where("? < start_date AND end_date < ?", start_date, end_date).exists?
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_rooms_list.html.erb
<br />
<h3><%= @rooms.count %>件見つかりました。</h3>

<% if @rooms.any? %> <% @rooms.each do |room| %>

<div class="card"></div>
<div class="row" style="margin-top: 50px; margin-left: 30px" ;>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>施設画像</th>
        <th>施設名</th>
        <th>住所</th>
        <th>施設詳細</th>
        <th>施設料金（一泊）</th>
        <th>予約</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
          <% if room %> <%= link_to room_path(room), data: { turbolinks: false} do %> 
          <% if room.photos.attached? %> <%= image_tag room.photos.first, style: "width: 230px;" %><br />
          <% else %> 
          <%= image_tag "default_image_room.png", style: "width: 230px;" %> 
          <% end %> 
          <%= room.listing_name %> 
          <% end %>
          <% end %>
        </td>

        <td><%= link_to room.room_type, room_path(room), data: { turbolinks: false} %></td>

        <td><%= room.address %></td>

        <td><%= room.summary %></td>

        <td>
          <div class="btn btn-danger btn-block disabled"><%= number_to_currency(room.price) %></div>
        </td>

        <td><%= link_to "詳細はこちら", room, data: {turbolinks: false}%></td>
      </tr>
    </tbody>
  </table>
</div>
<% end %> <% else %>
<p>該当する部屋はありません</p>
<% end %>

<style>
  .card {
    margin-left: 18px;
  }
  h3 {
    margin-left: 18px;
  }
</style>

app/views/rooms/create.html.erb
<h1>Rooms#create</h1>
<p>Find me in app/views/rooms/create.html.erb</p>

app/views/rooms/new.html.erb
<br />
<div class="col-sm-5" style="margin: 0 auto">
  <div class="card text-center">
    <br />
    <h2 class="card-header text-center">新規登録</h2>
    <div class="card-body">
      <br />

      <%= form_with(model: @room, method: :post, multipart: true, data:{turbo:false}) do |f| %> <%= render "shared/error", obj:@room %>

      <div class="form-group">
        <%= f.label :施設名, class: "label" %><br />
        <%= f.text_field :room_type, size: 23 %>
      </div>
      <br />

      <div class="form-group">
        <%= f.label :施設説明, class: "label" %><br />
        <%= f.text_area :summary %>
      </div>
      <br />

      <div class="form-group">
        <%= f.label :料金（一泊あたり）, class: "label" %><br />
        <%= f.text_field :price, size: 23 %>
      </div>
      <br />

      <div class="form-group">
        <%= f.label :住所, class: "label" %><br />
        <%= f.text_area :address %>
      </div>
      <br />

      <div class="field">
        <%= f.label :施設画像 %>
        <br />
        <%= f.file_field :photos %>
      </div>

      <br />
      <div><%= f.submit "登録する", class: "btn btn-primary btn-block" %></div>
      <br />
      <% end %>
    </div>
  </div>
</div>
<br />

app/views/rooms/photo_upload.html.erb
<br />
<div class="row">
  <div class="col-md-3"><%= render "room_menu" %></div>
  <div class="col-md-9">
    <div class="row">
      <div class="col-sm-9">
        <br />
        <div class="card text-center">
          <h4 class="card-header text-center">お部屋の写真登録</h4>
          <div class="card-body" style="margin-left: 50px">
            <br />

            <div class="dropzone" id="myDropzone" style="height: 200px; width: 60px" action="/rooms/<%= @room.id %>/upload__photo"></div>
            <br />
            <div class="container" style="margin-left: 20px">
              <div class="row">
                <% @room.photos.each do |photo| %>

                <div class="col-md-3">
                  <figure><%= image_tag url_for(photo), style: "width: 100%;" %></figure>

                  <%= link_to "削除", delete_photo_room_url(photo_id: photo.id, id: @room.id), method: :delete, data: { confirm: "本当に削除しますか?"}, style: "z-index: 100; margin-top: -15px;
                  margin-bottom: 20px; font-size: 10px;", class: "btn btn-outline-danger btn-sm" %>
                </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  Droozone.options.myDropzone = {
    paramName: "file",
    maxFilesize: 2,
    acceptedFiles: "image/*",
    init: function () {
      this.on("complete", function (file) {
        location.reload();
      });
    },
  };
</script>

app/views/rooms/show.html.erb
<div class="row" style="margin-left: 10px; margin-right: 10px">
  <div class="col-md-8">
    <br />

    <div class="row">
      <div class="col-md-11">
        <div class="card">
          <div class="card-body">
            <h3>施設の詳細</h3>

            <p>
              <% if @room %> <%= link_to room_path(@room), data: { turbolinks:false} do %> <% if @room.photos.attached? %> <%= image_tag@room.photos.first, style: "width: 230px;" %><br />
              <% else %> <%= image_tag "default_image_room.png", style: "width: 230px;" %> <% end %> <% end %> <% end %>
            </p>

            <p><%= @room.room_type %></p>
            <p><%= @room.summary %></p>
            <p><%= number_to_currency(@room.price) %>（一泊）</p>

            <div class="card" style="width: 24rem; margin-left: 70px">
              <div class="card-body">
                <%= form_with(model: [@room, @room.reservations.new], local: true ) do |f| %> <%= render "shared/error", obj:@reservation%>

                <table>
                  <tr>
                    <th><%= f.label :start_date ,"チェックイン" %></th>
                    <td><%= f.date_field :start_date, min: Time.zone.now %></td>
                  </tr>
                  <tr>
                    <th><%= f.label :end_date ,"チェックアウト" %></th>
                    <td><%= f.date_field :end_date, min: Time.zone.now %></td>
                  </tr>
                  <tr>
                    <th><%= f.label :人数（半角数字） %></th>
                    <td><%= f.number_field :number_of_guests %></td>
                  </tr>
                </table>

                <br />
                <%= f.submit "予約する", id: "btn_book", class: "btn btn-danger btn-block"%>
              </div>
            </div>

            <%= link_to "戻る", :back %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>
<br />

app/views/rooms/update.html.erb
<h1>Rooms#update</h1>
<p>Find me in app/views/rooms/update.html.erb</p>